Repository GSG-G11/fresh-pet, pull requests merged in 2022-04, with the labels that each got.

#6 Get all products from backend
  example.env
  server/app.js
  server/controllers/authController.js
  server/controllers/index.js
  server/controllers/productsController.js
  server/controllers/userController.js
  server/database/queries/queries.js
  server/routes/authRoutes.js
  server/routes/productRoutes.js
  server/routes/userRoutes.js
Labels: Awaiting Review

#8 7 frontend products section
  client/src/App.js
  client/src/components/Products/Product.jsx
  client/src/components/Products/ProductSection.css
  client/src/components/Products/ProductsFilter.jsx
  client/src/components/Products/ProductsList.jsx
Labels: Awaiting Review

#9 get single product backend
  client/package-lock.json
  client/yarn.lock
  server/controllers/getSingleProduct.js
  server/controllers/index.js
  server/database/queries/getSingleProductQuery.js
  server/routes/productRoutes.js
  yarn.lock
Labels: Awaiting Review

#13 get single product page
  client/public/favicon.ico
  client/public/favicon.png
  client/public/index.html
  client/public/logo192.png
  client/public/logo512.png
  client/public/manifest.json
  client/public/robots.txt
  client/src/App.js
  client/src/components/NotFound/NotFound.jsx
  client/src/components/Products/Product.jsx
  client/src/components/Products/ProductDetails.jsx
Labels: Awaiting Review

#14 Add Search function
  client/src/components/Products/ProductsFilter.jsx
  client/src/components/Products/ProductsList.jsx
Labels: Awaiting Review

#17 Add Filter by Sub Category
  client/src/components/Products/Product.jsx
  client/src/components/Products/ProductSection.css
  client/src/components/Products/ProductsFilter.jsx
  client/src/components/Products/ProductsList.jsx
Labels: Awaiting Review

#18 create pet category
  client/public/img/bird.png
  client/public/img/cat.png
  client/public/img/dog.png
  client/public/img/fish.png
  client/public/img/green-background.jpg
  client/public/img/horseback.png
  client/public/img/red-background.jpg
  client/public/img/treats.png
  client/public/img/yellow-background.jpg
  client/public/index.html
  client/public/style.css
  client/src/App.js
  client/src/components/Products/PetFilter.jsx
  client/src/components/Products/ProductSection.css
  client/src/components/Products/ProductsList.jsx
  client/src/components/Products/petFilterStyle.css
Labels: Awaiting Review

#19 create the website header
  client/package.json
  client/src/App.js
  client/src/components/Assets/background.jpg
  client/src/components/Assets/bird.png
  client/src/components/Assets/book-now.png
  client/src/components/Assets/cat.png
  client/src/components/Assets/dog.png
  client/src/components/Assets/fish.png
  client/src/components/Assets/green-background.jpg
  client/src/components/Assets/horseback.png
  client/src/components/Assets/logo.png
  client/src/components/Assets/red-background.jpg
  client/src/components/Assets/treats.png
  client/src/components/Assets/yellow-background.jpg
  client/src/components/Header/Header.css
  client/src/components/Header/Header.jsx
  client/src/components/Header/LandingImage.jsx
  client/yarn.lock
Labels: Done

#21 Add Styling to Homepage
  client/src/App.js
  client/src/components/Header/Header.css
  client/src/components/Header/Header.jsx
  client/src/components/Products/ProductSection.css
  client/src/components/Products/petFilterStyle.css
Labels: Awaiting Review

#24 create delete feature frontend
  client/src/App.js
  client/src/components/Products/Product.jsx
  client/src/components/Products/ProductsList.jsx
Labels: Awaiting Review

#25 Fix delete backend
  server/controllers/productsController.js
  server/database/queries/queries.js
  server/routes/productRoutes.js
Labels: Awaiting Review

#23 Frontend backend create add product feture
  .eslintrc.json
  client/.gitignore
  client/package-lock.json
  client/package.json
  client/public/index.html
  client/src/App.js
  client/src/components/Forms/CreateProduct.jsx
  client/src/components/Forms/UpdateProduct.jsx
  client/src/components/Forms/form.module.css
  client/src/components/Forms/index.js
  client/src/components/Modal/index.jsx
  client/src/components/Modal/modal.module.css
  client/src/components/Products/Product.jsx
  client/src/components/Products/ProductSection.css
  client/src/components/Products/ProductsFilter.jsx
  client/src/components/Products/ProductsList.jsx
  client/src/components/index.js
  client/src/index.css
  client/yarn.lock
  package-lock.json
  package.json
  server/app.js
  server/controllers/errorController.js
  server/controllers/index.js
  server/controllers/productsController.js
  server/database/queries/queries.js
  server/routes/productRoutes.js
  server/utils/CustomError.js
  server/utils/index.js
  server/utils/validation/createProductValidationSchema.js
  server/utils/validation/index.js
Labels: Awaiting Review

#27 fix images paths
  client/public/img/background.jpg
  client/public/img/book-now.png
  client/public/img/logo.png
  client/src/components/Assets/bird.png
  client/src/components/Assets/cat.png
  client/src/components/Assets/dog.png
  client/src/components/Assets/fish.png
  client/src/components/Assets/green-background.jpg
  client/src/components/Assets/horseback.png
  client/src/components/Assets/red-background.jpg
  client/src/components/Assets/treats.png
  client/src/components/Assets/yellow-background.jpg
  client/src/components/Header/Header.css
  client/src/components/Header/Header.jsx
  client/src/components/Header/LandingImage.jsx
Labels: Awaiting Review

#30 28 create update product backend
  server/controllers/index.js
  server/controllers/productsController.js
  server/database/queries/queries.js
  server/routes/productRoutes.js
Labels: Awaiting Review

#35 Create update product backend - new Feature
  client/src/App.js
  client/src/components/Forms/form.module.css
  client/src/components/Header/Header.css
  client/src/components/Header/index.js
  client/src/components/Modal/Modal.jsx
  client/src/components/Modal/index.js
  client/src/components/Modal/modal.module.css
  client/src/components/NotFound/index.js
  client/src/components/Products/PetFilter.jsx
  client/src/components/Products/ProductsList.jsx
  client/src/components/Products/index.js
  client/src/components/index.js
  client/src/index.css
  server/controllers/index.js
  server/controllers/productsController.js
  server/database/queries/queries.js
  server/utils/index.js
  server/utils/validation/index.js
  server/utils/validation/productValidationSchema.js
Labels: Done

#29 filter pet
  .gitignore
  client/src/components/Forms/CreateProduct.jsx
  client/src/components/Forms/form.module.css
  client/src/components/Header/LandingImage.jsx
  client/src/components/Products/PetFilter.jsx
  client/src/components/Products/Product.jsx
  client/src/components/Products/ProductsFilter.jsx
  client/src/components/Products/ProductsList.jsx
  client/yarn.lock
  package-lock.json
  yarn.lock
Labels: Awaiting Review

#38 Create Component for each button
  client/src/components/Buttons/AddToCard.jsx
  client/src/components/Buttons/Delete.jsx
  client/src/components/Buttons/Edit.jsx
  client/src/components/Products/Product.jsx
Labels: Awaiting Review, Done

#40 Frontend update product
  client/public/img/background.jpg
  client/public/img/book-now.png
  client/src/App.js
  client/src/components/Buttons/Delete.jsx
  client/src/components/Buttons/Edit.jsx
  client/src/components/Buttons/index.js
  client/src/components/Forms/CreateProduct.jsx
  client/src/components/Forms/UpdateProduct.jsx
  client/src/components/Header/Header.css
  client/src/components/Header/LandingImage.jsx
  client/src/components/Products/PetFilter.jsx
  client/src/components/Products/Product.jsx
  client/src/components/Products/ProductsList.jsx
  client/src/components/index.js
Labels: Done

#41 style product page
  client/src/components/Header/Header.jsx
  client/src/components/Products/ProductDetails.jsx
  client/src/components/Products/ProductSection.css
  client/src/components/Products/productPageStyle.css
Labels: Done

#47 Fix bug
  client/src/components/Products/ProductsList.jsx
Labels: Done

#49 Update add to card torstar
  client/public/index.html
  client/public/style.css
  client/src/App.js
  client/src/components/Buttons/AddToCard.jsx
  client/src/components/Buttons/Delete.jsx
  client/src/components/Cart/Cart.jsx
  client/src/components/Header/Header.jsx
  client/src/components/Products/Product.jsx
  client/src/components/Products/ProductSection.css
  client/src/components/Products/ProductsFilter.jsx
  client/src/components/Products/ProductsList.jsx
  client/src/index.css
  client/src/index.js
  server/app.js
  server/controllers/clientController.js
  server/controllers/index.js
  server/middlewares/errorHandler.js
  server/middlewares/index.js
  server/middlewares/verifyToken.js
  server/routes/apis/index.js
  server/routes/apis/productRoutes.js
  server/routes/client/index.js
  server/routes/index.js
Labels: Done

#55 51 hero content
  client/public/img/background.jpg
  client/public/img/bone.png
  client/src/components/Header/Header.css
  client/src/components/Header/LandingImage.jsx
  client/src/components/Products/ProductsList.jsx
  client/src/components/Products/petFilterStyle.css
Labels: Awaiting Review

#61 52 loading and cart add products details
  client/src/App.js
  client/src/components/Buttons/AddToCard.jsx
  client/src/components/Products/ProductDetails.jsx
  client/src/components/Products/ProductsList.jsx
  client/src/components/Products/productPageStyle.css
Labels: Awaiting Review

#62 Update function login and add username and fix style it
  client/src/App.js
  client/src/components/Forms/LoginForm.jsx
  client/src/components/Forms/index.js
  client/src/components/Header/Header.css
  client/src/components/Header/Header.jsx
  client/src/components/Products/ProductSection.css
  client/src/components/index.js
Labels: Awaiting Review

#63 53 price filter
  client/package.json
  client/src/components/Cart/Cart.jsx
  client/src/components/Cart/Counter.jsx
  client/src/components/Cart/cartStyle.css
  client/src/components/NotFound/NotFound.jsx
  client/src/components/Products/PetFilter.jsx
  client/src/components/Products/PriceFilter.jsx
  client/src/components/Products/Product.jsx
  client/src/components/Products/ProductSection.css
  client/src/components/Products/ProductsList.jsx
  client/src/components/Products/index.js
  client/src/components/Products/petFilterStyle.css
  client/src/index.css
Labels: Awaiting Review

#60 fix build paths and change the npm with yarn
  .gitignore
  client/.gitignore
  client/package.json
  package.json
  server/app.js
  yarn.lock
Labels: Done

#69 fix responsive
  client/public/img/cat-icon.png
  client/public/img/dog-icon.png
  client/public/img/dove-icon.png
  client/public/img/fish-icon.png
  client/public/img/horse-icon.png
  client/src/components/Cart/Counter.jsx
  client/src/components/Header/Header.css
  client/src/components/Header/LandingImage.jsx
  client/src/components/Products/PriceFilter.jsx
  client/src/components/Products/ProductSection.css
  client/src/components/Products/ProductsList.jsx
  client/src/components/Products/petFilterStyle.css
Labels: Awaiting Review

#74 Fix filtering
  client/public/img/footer.png
  client/public/img/footer.webp
  client/src/App.js
  client/src/components/Footer/Footer.jsx
  client/src/components/Footer/footer.css
  client/src/components/Footer/index.js
  client/src/components/Products/ProductsList.jsx
  client/src/components/index.js
Labels: Awaiting Review

#75 Not found
  client/public/img/not-found.png
  client/src/components/Products/ProductsList.jsx
Labels: Done

#72 67 total cost feature
  client/src/App.js
  client/src/components/Buttons/AddToCard.jsx
  client/src/components/Cart/Cart.jsx
  client/src/components/Cart/Counter.jsx
  client/src/components/Cart/cartStyle.css
Labels: Awaiting Review

#77 Fix Bug In Add To Cart In Single Page
  client/src/App.js
  client/src/components/Footer/footer.css
  client/src/components/Products/ProductDetails.jsx
Labels: Done

#79 Fix Bug in Filter by price and fix class name and remove not needed input
  client/src/components/Products/PriceFilter.jsx
  client/src/components/Products/ProductDetails.jsx
  client/src/components/Products/ProductsList.jsx
Labels: Awaiting Review

#80 Update Readme
  README.md
Labels: Done
